import { test, expect, type Page } from '@playwright/test'
const password = 'Test-Password-123!'
async function register(page: Page, email: string) {
  await page.getByRole('button', { name: 'New here? Create an account' }).click()
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Account created')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Log history' })).toBeVisible()
}
test('accounts, private logs, filters, reload, logout and another user', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill(`missing-${Date.now()}@example.test`)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Invalid email or password')
  await register(page, `first-${Date.now()}@example.test`)
  await expect(page.getByText('No logs here yet.')).toBeVisible()
  await page.getByLabel('Message', { exact: true }).fill('Private warning from first account')
  await page.getByLabel('Level', { exact: true }).selectOption('warning')
  await page.getByRole('button', { name: 'Save log' }).click()
  await expect(page.getByRole('cell', { name: 'Private warning from first account' })).toBeVisible()
  await page.getByLabel('Filter by level').selectOption('error')
  await expect(page.getByText('No logs here yet.')).toBeVisible()
  await page.getByLabel('Filter by level').selectOption('warning')
  await expect(page.getByRole('cell', { name: 'Private warning from first account' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('cell', { name: 'Private warning from first account' })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  await register(page, `second-${Date.now()}@example.test`)
  await expect(page.getByText('No logs here yet.')).toBeVisible()
  await expect(page.getByText('Private warning from first account')).toHaveCount(0)
})
test('pagination, recoverable errors and expired sessions', async ({ page }) => {
  await page.goto('/')
  await register(page, `paging-${Date.now()}@example.test`)
  await page.evaluate(async () => {
    for (let index = 0; index < 26; index++) {
      const { token } = await fetch('/api/auth/csrf').then(r => r.json())
      const response = await fetch('/api/logs', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': token }, body: JSON.stringify({ message: `Entry ${index}`, level: 'info', occurredAt: new Date().toISOString() }) })
      if (!response.ok) throw new Error(`Create failed: ${response.status}`)
    }
  })
  await page.reload()
  await expect(page.getByText('Page 1 of 2')).toBeVisible()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByText('Page 2 of 2')).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Entry 0', exact: true })).toBeVisible()
  await page.route('**/api/logs?*', route => route.fulfill({ status: 503, contentType: 'application/problem+json', body: JSON.stringify({ title: 'Temporarily unavailable' }) }))
  await page.getByRole('button', { name: 'Previous', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.unroute('**/api/logs?*')
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByText('Page 1 of 2')).toBeVisible()
  await page.context().clearCookies()
  await page.getByLabel('Filter by level').selectOption('warning')
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  await expect(page.getByRole('table')).toHaveCount(0)
})
