import { test, expect } from '@playwright/test'
import { emailLink, followLink, password, registerVerified, signIn } from './account-helpers'
test.use({ viewport: { width: 375, height: 900 } })
test('verification is required, links are single use, and password recovery works', async ({ page }) => {
  const email = `recovery-${Date.now()}@example.test`
  await page.goto('/')
  await page.getByRole('button', { name: 'New here? Create an account' }).click()
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Account created')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Verify your email')
  const verification = await emailLink(page.request, email, 'Verify your IGDash email')
  await followLink(page, verification)
  await page.getByRole('button', { name: 'Confirm email', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Email verified')
  await followLink(page, verification)
  await page.getByRole('button', { name: 'Confirm email', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('invalid or has expired')
  await page.getByRole('button', { name: 'Request a new link', exact: true }).click()
  await page.getByRole('button', { name: 'Forgot password?', exact: true }).click()
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByRole('button', { name: 'Send reset link', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('If this account is eligible')
  const reset = await emailLink(page.request, email, 'Reset your IGDash password')
  await followLink(page, reset)
  await page.getByLabel('New password', { exact: true }).fill('New-Password-456!')
  await page.getByRole('button', { name: 'Reset password', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Password reset')
  await page.getByRole('button', { name: 'Continue to sign in', exact: true }).click()
  await signIn(page, email, 'New-Password-456!')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
test('settings change password, confirm email, preserve logs and revoke a remote session', async ({ page, browser }) => {
  const email = `settings-${Date.now()}@example.test`
  const changed = `changed-${Date.now()}@example.test`
  await page.goto('/')
  await registerVerified(page, email)
  await page.getByLabel('Message', { exact: true }).fill('Account changes keep this private log')
  await page.getByRole('button', { name: 'Save log', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Account changes keep this private log', exact: true })).toBeVisible()
  const otherContext = await browser.newContext()
  try {
    const other = await otherContext.newPage()
    await other.goto(process.env.BASE_URL || 'http://localhost:5173')
    await signIn(other, email)
    await page.getByRole('button', { name: 'Account settings', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Active sessions', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Revoke session', exact: true }).click()
    await other.reload()
    await expect(other.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
    await page.getByLabel('Current password', { exact: true }).fill(password)
    await page.getByLabel('New password', { exact: true }).fill('Changed-Password-789!')
    await page.getByRole('button', { name: 'Change password', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
    await signIn(page, email, 'Changed-Password-789!')
    await page.getByRole('button', { name: 'Account settings', exact: true }).click()
    await page.getByLabel('New email', { exact: true }).fill(changed)
    await page.getByLabel('Current password for email change', { exact: true }).fill('Changed-Password-789!')
    await page.getByRole('button', { name: 'Send email confirmation', exact: true }).click()
    await expect(page.getByRole('status')).toContainText('Check your new inbox')
    const link = await emailLink(page.request, changed, 'Confirm your IGDash email change')
    await followLink(page, link)
    await page.getByRole('button', { name: 'Confirm email change', exact: true }).click()
    await expect(page.getByRole('status')).toContainText('Email updated')
    await page.getByRole('button', { name: 'Continue to sign in', exact: true }).click()
    await signIn(page, changed, 'Changed-Password-789!')
    await expect(page.getByRole('cell', { name: 'Account changes keep this private log', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Account settings', exact: true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Sign out all sessions', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  } finally { await otherContext.close() }
})
