import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
test.use({ viewport: { width: 375, height: 900 } })
async function register(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'New here? Create an account' }).click()
  await page.getByLabel('Email', { exact: true }).fill(`features-${Date.now()}@example.test`)
  await page.getByLabel('Password', { exact: true }).fill('Test-Password-123!')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Account created')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Log history' })).toBeVisible()
}
test('edit, normalized tags, combined filters, summary, export and delete confirmation', async ({ page }) => {
  await register(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByLabel('Message', { exact: true }).fill('Review the release notes')
  await page.getByLabel('Level', { exact: true }).selectOption('warning')
  await page.getByLabel('Tags', { exact: true }).fill(' WORK, learning, work ')
  await page.getByLabel('Occurred at', { exact: true }).fill('2026-10-06T12:00')
  await page.getByRole('button', { name: 'Save log', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'Review the release notes' })).toContainText('learning')
  await page.getByRole('button', { name: 'Edit log: Review the release notes', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Edit log', exact: true })).toBeVisible()
  await expect(page.getByLabel('Message', { exact: true })).toBeFocused()
  await page.getByLabel('Message', { exact: true }).fill('Updated release review')
  await page.getByLabel('Tags', { exact: true }).fill('work, release')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edit log: Updated release review', exact: true })).toBeVisible()
  await page.getByLabel('Search messages').fill('RELEASE')
  await page.getByLabel('From date', { exact: true }).fill('2026-10-06')
  await page.getByLabel('To date', { exact: true }).fill('2026-10-06')
  await page.getByLabel('Filter by tag').selectOption('release')
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('1 log')
  const summary = page.getByRole('region', { name: 'Activity summary' })
  await expect(summary.locator('dd').first()).toHaveText('1')
  await expect(summary.locator('dd').nth(2)).toHaveText('1')
  await page.getByText('View daily counts', { exact: true }).click()
  await expect(summary.getByRole('table')).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSV', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('igdash-logs.csv')
  const file = await download.path(); expect(file).toBeTruthy()
  const csv = await readFile(file!, 'utf8'); expect(csv).toContain('Updated release review'); expect(csv).toContain('release;work')
  await page.getByRole('button', { name: 'Delete log: Updated release review', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Delete this log?' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Keep log', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Delete log: Updated release review', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm delete', exact: true }).click()
  await expect(page.getByText('No logs here yet.', { exact: true })).toBeVisible()
  await expect(summary.locator('dd').first()).toHaveText('0')
})
test('export includes further pages, empty searches and invalid date feedback', async ({ page }) => {
  await register(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.evaluate(async () => {
    for (let index = 0; index < 26; index++) {
      const { token } = await fetch('/api/auth/csrf').then(r => r.json())
      const response = await fetch('/api/logs', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': token }, body: JSON.stringify({ message: `Export entry ${index}`, level: 'info', occurredAt: '2026-10-06T12:00:00Z', tags: ['export'] }) })
      if (!response.ok) throw new Error(`Create failed: ${response.status}`)
    }
  })
  await page.reload()
  await expect(page.getByText('Page 1 of 2', { exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSV', exact: true }).click()
  const file = await (await downloadPromise).path()
  const csv = await readFile(file!, 'utf8'); expect(csv.trim().split('\r\n')).toHaveLength(27)
  await page.getByLabel('From date', { exact: true }).fill('2026-10-07')
  await page.getByLabel('To date', { exact: true }).fill('2026-10-06')
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Start date must be on or before end date')
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await page.getByLabel('Search messages').fill('nothing-matches-this')
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click()
  await expect(page.getByText('No logs here yet.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await expect(page.getByText('Page 1 of 2', { exact: true })).toBeVisible()
})
